Bootstrap application from Liberu Laravel Boilerplate

diff --git a/.docker/healthcheck b/.docker/healthcheck
--- a/.docker/healthcheck
+++ b/.docker/healthcheck
@@ -8,25 +8,25 @@ if [ "${container_mode}" = "http" ]; then
     php "${ROOT}/artisan" octane:status
 elif [ "${container_mode}" = "horizon" ]; then
     php "${ROOT}/artisan" horizon:status
-elif [ "${container_mode}" = "scheduler" ]; then
-    if [ "$(supervisorctl status scheduler:scheduler_0 | awk '{print tolower($2)}')" = "running" ]; then
-        exit 0
-    else
-        echo "Scheduler healthcheck failed."
-        exit 1
-    fi
 elif [ "${container_mode}" = "reverb" ]; then
     if [ "$(supervisorctl status reverb:reverb_0 | awk '{print tolower($2)}')" = "running" ]; then
         exit 0
     else
-        echo "Reverb healthcheck failed."
+        echo "Healthcheck failed."
+        exit 1
+    fi
+elif [ "${container_mode}" = "scheduler" ]; then
+    if [ "$(supervisorctl status scheduler:scheduler_0 | awk '{print tolower($2)}')" = "running" ]; then
+        exit 0
+    else
+        echo "Healthcheck failed."
         exit 1
     fi
 elif [ "${container_mode}" = "worker" ]; then
     if [ "$(supervisorctl status worker:worker_0 | awk '{print tolower($2)}')" = "running" ]; then
         exit 0
     else
-        echo "Worker healthcheck failed."
+        echo "Healthcheck failed."
         exit 1
     fi
 else
